# Generated by Django 2.2.2 on 2019-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('CCPC', 'CCPC'), ('ICPC', 'ICPC'), ('其他', '其他'), ('大事件', '大事件'), ('天梯赛', '天梯赛'), ('浙大赛', '浙大赛'), ('浙江省赛', '浙江省赛')], max_length=10)),
                ('time', models.DateField()),
            ],
        ),
    ]
