# Generated by Django 2.2.5 on 2019-09-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='detail',
            field=models.CharField(max_length=5000),
        ),
    ]
