# Generated by Django 2.2.5 on 2019-09-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honors', '0002_auto_20190924_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='honor',
            name='intro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='honor',
            name='detail',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='honor',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
