# Generated by Django 2.2.5 on 2019-09-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('-created',)},
        ),
    ]
