# Generated by Django 2.2.2 on 2019-06-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('教练', '教练'), ('普通用户', '普通用户'), ('退役队员', '退役队员'), ('队员', '队员')], default='普通用户', max_length=10)),
                ('biography', models.CharField(blank=True, default='', max_length=5000)),
                ('avatar', models.ImageField(default='', storage=user.storage.OverwriteStorage(), upload_to='avatar')),
                ('name', models.CharField(blank=True, default='', max_length=10)),
                ('sid', models.CharField(blank=True, default='', max_length=10)),
                ('level', models.CharField(blank=True, default='', max_length=10)),
                ('graduate', models.CharField(blank=True, default='', max_length=50)),
                ('work', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'auth_profile',
                'ordering': ('created_at',),
            },
        ),
    ]
