# Generated by Django 2.2.2 on 2019-08-12 07:50

from django.db import migrations, models
import user.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', storage=user.storage.OverwriteStorage(), upload_to='avatar'),
        ),
    ]
